version: "3.8"

services:
  frontend:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=AIzaSyClgA0TxX3EWABI1HiItjfg_tPHCMncDPY
